// Shim for Pinocchio generated header

#ifndef PINOCCHIO_WARNING_HPP
#define PINOCCHIO_WARNING_HPP

#define PINOCCHIO_COMPILER_DIAGNOSTIC_PUSH
#define PINOCCHIO_COMPILER_DIAGNOSTIC_POP
#define PINOCCHIO_COMPILER_DIAGNOSTIC_IGNORED_DEPRECECATED_DECLARATIONS

#endif // PINOCCHIO_WARNING_HPP
